### ISSUE TITLE
Suggestions for TDS docs

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/tour-de-sol#10]
* Split up “Connecting your Validator” into a connecting and a staking section
* Add a link to the network explorer in the “Monitoring your validator” section since that’s also a mechanism to monitor the state of your validator
* In the "Monitoring your validator" section the description of `solana get-slot` isn't clear whether the slot returned is the validator's or the cluster's.  Expanding this description to describe how to get both would help.
* The staking docs talk about staking once the validator has caught up but doesn't describe or link to info about how to know when its caught up.
* Mentioning `solana-keygen pubkey <file>` would help folks know how to get the exact form of their keys that match `spy` and the network explorer output

**Comment by CriesofCarrots** [comment]
Closed by https://github.com/solana-labs/tour-de-sol/commit/3290ad2eea00ace774fad3fb9ae49fbfa728c253
