### ISSUE TITLE
Winner Tool: Add script for running against the TdS cluster

### ISSUE THREAD

**Issue by jstarry** [solana-labs/tour-de-sol#13]
From: https://github.com/solana-labs/tour-de-sol/pull/12/files/87bc2bd1c94785590fa48d6c725586bbae23599b#r334517564
> [Add a] new shell script like https://github.com/solana-labs/tour-de-sol/blob/master/bench-tps.sh that runs the tool with all the right settings against the actual TdS cluster.

**Comment by mvines** [comment]
Done, it's ramp-tps
