### ISSUE TITLE
Ramp TPS: Award stake based on skipped block percentage

### ISSUE THREAD

**Issue by jstarry** [solana-labs/tour-de-sol#67]
#### Problem
Slow nodes in a network can drag down TPS performance by skipping slots and never get penalized for doing so. This prevents the Ramp TPS tool from pushing the network to a higher average TPS.

#### Solution
Do not award stake to any remaining active validators which skip a certain percentage of their allotted leader slots

**Comment by mvines** [comment]
A bunch of code from https://github.com/solana-labs/solana/blob/7329d4bf3a40e71239a02367380e209a2b5f4919/cli/src/cluster_query.rs#L423-L570 could be refactored into functions that can be reused in this implementation
